### ISSUE TITLE
No module named 'cv2'

### ISSUE THREAD

**Issue by fly800** [gordtulloch/mlCloudDetect#2]
When I run mlCloudDectect.py I get the following error:

(.venv) admin@raspberrypi:~/mlCloudDetect $ python3 mlCloudDetect.py 45. -66 10 latest.jpg
Traceback (most recent call last):
  File "/home/admin/mlCloudDetect/mlCloudDetect.py", line 14, in <module>
    from mcpClouds import McpClouds
  File "/home/admin/mlCloudDetect/mcpClouds.py", line 8, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by fly800** [comment]
To solve this problem, I needed to install OpenCV.
To see if OpenCV is installed : pip show opencv-python
To install OpenCV: pip install opencv-python

**Comment by gordtulloch** [comment]
Updated requirements.txt thanks!
