### ISSUE TITLE
Suggestion: Cropping area for training/detection

### ISSUE THREAD

**Issue by zaphus** [gordtulloch/mlCloudDetect#4]
I would like to ensure that the training algorithm isn't learning from the wrong cues - for instance most of my cloud examples are from September, and clear nights from October.  The date is written in the image pixel-perfect every time, and the algorithm could learn from that rather than the clouds.  it would also cater for repositioning of the allsky cam/etc or other incidental lighting that happens on the horizon

Could there be an .ini file parameter to specify the crop area of the image, either as x,y,w,h, or as a percentage of the center of the image?

**Comment by gordtulloch** [comment]
I turn off all text on the image when capturing for training, it's easy to do in the indi-allsky config. You don't mention what software you're using but I imagine it's the same.  In any case the image is resized to 256,256 during the training process so any text is rendered unreadable.  

You can preprocess your images as you like before training - you can batch crop images with imagemagick for example. As I don't use this software myself (the clouds object has been incorporated into my observatory management system) I don't have time to do these kinds of customizations that are easily done in other ways. Thanks for your comments!

**Comment by zaphus** [comment]
No problem.  thanks - I'll create a fork and head off in my own direction!

**Comment by gordtulloch** [comment]
And therein lies the beauty of Open Source. Although you COULD just merge into this project as well. Good luck!
