### ISSUE TITLE
Quick question: Are you open to contribution?

### ISSUE THREAD

**Issue by hairlesshobo** [gordtulloch/mlCloudDetect#8]
First I want to say thanks! This is awesome and I see a TON of potential into making this a very useful tool. I actually stumbled on this while looking for DIY plans for building an IR-based cloud detection sensor and, as I recently deployed my own indi-allsky instance, this seemed like a perfect solution.

I don't see any sort of "contributing" file or anything so I wonder if you are open to contribution to this project. I am super impressed with what you have so far and I am currently working to integrate it into my setup. 

I have already dockerized it so that you don't get trapped in python dependency hell when deploying it, and I have quite a few plans for quality of live improvements (such as passing config via env variables, making more items configurable, etc). Plus I intend to add MQTT support (both input from indi-allsky as well as output to a different topic for easy integration into outside tools).  Even bouncing around with the idea of daylight cloud detection too using a second model. This daylight model could be very helpful for people who do solar imaging (I don't currently but would like to at some point).

Anyways, let me know if you are interested in outside contribution or not so that I know whether I should submit PRs for some/all of this stuff or if I should just keep them in my own fork for my own use.

Again, thanks for all the work you have already put into this!

**Comment by gordtulloch** [comment]
I'm happy to see additional contributors to this project provided it stays within the observatory safety scope.  CONTRIBUTING file created.
